
services:
  db:
    image: postgres:15
    container_name: sisyphus_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sisyphus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sisyphus_redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
